# Generated by Django 5.1.7 on 2025-03-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
